trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/*
pool:
  vmImage: 'Ubuntu 16.04'

steps:
# Validate ARM template
- task: AzureResourceGroupDeployment@2
  displayName: 'Validate ARM template'
  inputs:
    azureSubscription: $(serviceConnectionAzureSubscription)
    resourceGroupName: $(resourceGroupName)
    location: $(location)
    csmFile: infrastructure/azuredeploy.json
    overrideParameters: '-application_name $(applicationName) -docker_title_url $(ACR_SERVER) -docker_person_url $(ACR_SERVER) -docker_ui_url $(ACR_SERVER)'
    deploymentMode: Validation

# Copy ARM deployment JSON
- task: CopyFiles@2
  displayName: 'Copy ARM deployment JSON'
  inputs:
    contents: 'infrastructure/azuredeploy.json'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

# Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: package
    publishLocation: Container
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
