trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ui/*

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.13.0'
    failOnStandardError: 'true'
  displayName: 'Install Node.js'
- script: |
    npm install
  workingDirectory: ui/
  displayName: 'NPM Install Step'
- script: |
    npm run lint
  workingDirectory: ui/
  displayName: 'NPM Lint Step'
- script: |
    npm run test
  workingDirectory: ui/
  displayName: 'NPM Test Step'
- script: |
    npm run build
  workingDirectory: ui/
  displayName: 'NPM Build Step'
- script: |
    docker build -t $ACR_SERVER/$ACR_CONTAINER_TAG .
  workingDirectory: ui/
  displayName: 'Docker Build'
- script: |
    docker login $(ACR_SERVER) -u $(acrUsername) -p $(acrPassword)
  displayName: 'Docker Login'
- script: |
    docker push $ACR_SERVER/$ACR_CONTAINER_TAG
  displayName: 'Docker Push'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
