# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - api/*

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    docker build -t $(acrLoginServer)/$ACR_CONTAINER_TAG .
  workingDirectory: api/
  displayName: 'Docker Test, Build and Package'
- script: |
    docker login $(acrLoginServer) -u $(acrUsername) -p $(acrPassword)
  displayName: 'Docker Login'
- script: |
    docker push $acrLoginServer/$ACR_CONTAINER_TAG
  displayName: 'Docker Push'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
